import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const categories = [
  ['missing-rule', 'Missing rule implementations'],
  ['executable-config', 'Executable fixture configuration'],
  ['compiler', 'Svelte compiler capability'],
  ['invalid-spans', 'Invalid diagnostic or fix spans'],
  ['parser', 'Parser/compiler validation differences'],
  ['diagnostic-count', 'Diagnostic count differences'],
  ['diagnostic-message', 'Same count, different messages'],
  ['diagnostic-location', 'Same messages, different locations/order'],
  ['fix', 'Fix output or unexpected automatic fixes'],
  ['suggestions', 'Suggestions are the remaining blocker'],
  ['configuration', 'Unsupported parser/language configuration'],
];

const messages = (diags) => diags.map((diag) => diag.message).sort();

export function classify(issues) {
  if (issues.unsupported_rule) return 'missing-rule';
  if (issues.executable_configuration) return 'executable-config';
  if (issues.compiler_capability) return 'compiler';
  if (issues.diagnostic_spans || issues.fix_spans || issues.suggestion_spans) return 'invalid-spans';
  if (issues.parse_errors) return 'parser';
  if (issues.diagnostics) {
    const { expected, actual } = issues.diagnostics;
    if (expected.length !== actual.length) return 'diagnostic-count';
    if (JSON.stringify(messages(expected)) !== JSON.stringify(messages(actual))) return 'diagnostic-message';
    return 'diagnostic-location';
  }
  if (issues.diagnostic_count) return 'diagnostic-count';
  if (issues.fix_output || issues.unexpected_fix) return 'fix';
  if (issues.suggestions || issues.suggestion_capability) return 'suggestions';
  if (issues.parser_configuration || issues.language_configuration) return 'configuration';
  throw new Error(`Unclassified issues: ${JSON.stringify(issues)}`);
}

export function summarize(report) {
  if (!Array.isArray(report.cases) || !report.cases.length) throw new Error('Report contains no cases');
  const ids = new Set();
  const primary = new Map(categories.map(([id, label]) => [id, { id, label, count: 0, rules: {} }]));
  const dimensions = {};
  const totals = { pass: 0, gaps: 0, versionSkip: 0 };
  const versionSkips = {};
  for (const entry of report.cases) {
    if (ids.has(entry.id)) throw new Error(`Duplicate case: ${entry.id}`);
    ids.add(entry.id);
    if (entry.status === 'pass') {
      if (Object.keys(entry.issues).length) throw new Error(`Passing case has issues: ${entry.id}`);
      totals.pass++;
      continue;
    }
    if (entry.status === 'version_skip') {
      if (!entry.issues.version_skip) throw new Error(`Missing version skip reason: ${entry.id}`);
      totals.versionSkip++;
      (versionSkips[entry.rule] ??= []).push({ id: entry.id, reasons: entry.issues.version_skip });
      continue;
    }
    if (entry.status !== 'gap') throw new Error(`Unknown case status: ${entry.status}`);
    totals.gaps++;
    for (const dimension of Object.keys(entry.issues)) {
      const detail = dimensions[dimension] ??= { count: 0, rules: {} };
      detail.count++;
      detail.rules[entry.rule] = (detail.rules[entry.rule] ?? 0) + 1;
    }
    const group = primary.get(classify(entry.issues));
    group.count++;
    (group.rules[entry.rule] ??= []).push({ id: entry.id, dimensions: Object.keys(entry.issues).sort() });
  }
  if (Object.keys(totals).some((key) => totals[key] !== report.totals[key])) throw new Error('Report totals do not match case inventory');
  return { revision: report.revision, manifestHash: report.manifestHash, environment: report.environment,
    totals, method: 'Each gap is assigned to its first blocker. Dimensions retain all overlapping issues. Category labels describe observed differences, not proven root causes.',
    categories: [...primary.values()].filter((group) => group.count), dimensions, versionSkips };
}

export function markdown(summary) {
  const out = ['# Upstream parity gap inventory', '',
    'Generated by `node scripts/summarize-parity.mjs`. See [the commit plan](upstream-parity-plan.md) for the proposed work order. Full case IDs and secondary issues are in [the JSON inventory](upstream-parity-gaps.json).', '',
    `Pinned revision: \`${summary.revision}\`. Current results: **${summary.totals.pass} matches, ${summary.totals.gaps} gaps, ${summary.totals.versionSkip} version skips**.`, '',
    '## First blocker per case', '',
    'These groups are mutually exclusive and sum to the gap total. A location/order case has the same message multiset as upstream, but can still need a fix or suggestion. Resolve its secondary issues before counting it as complete.', '',
    '| Category | Cases |', '| --- | ---: |',
    ...summary.categories.map((group) => `| ${group.label} | ${group.count} |`), '',
    '## Overlapping issues', '',
    'These counts overlap. A case can have several issues, so this table does not sum to the gap total.', '',
    '| Issue | Cases |', '| --- | ---: |',
    ...Object.entries(summary.dimensions).sort(([, a], [, b]) => b.count - a.count).map(([name, detail]) => `| \`${name}\` | ${detail.count} |`), '',
    '## Rules in each group', ''];
  for (const group of summary.categories) {
    out.push(`### ${group.label}`, '', '| Rule | Cases |', '| --- | ---: |',
      ...Object.entries(group.rules).sort(([, a], [, b]) => b.length - a.length).map(([rule, cases]) => `| ${rule} | ${cases.length} |`), '');
  }
  out.push('## Version skips', '',
    'These are outside the declared Svelte 5 environment, not implementation failures. Keep them separate from the gap backlog.', '',
    '| Rule | Cases |', '| --- | ---: |',
    ...Object.entries(summary.versionSkips).sort(([, a], [, b]) => b.length - a.length).map(([rule, cases]) => `| ${rule} | ${cases.length} |`), '');
  return out.join('\n');
}

function main() {
  const [input = 'reports/upstream-parity.json', jsonOutput = 'docs/research/upstream-parity-gaps.json', markdownOutput = 'docs/research/upstream-parity-gaps.md', ...extra] = process.argv.slice(2);
  if (extra.length) throw new Error('Usage: node scripts/summarize-parity.mjs [report.json] [inventory.json] [inventory.md]');
  const summary = summarize(JSON.parse(readFileSync(input, 'utf8')));
  for (const [filename, content] of [[jsonOutput, JSON.stringify(summary, null, 2) + '\n'], [markdownOutput, markdown(summary)]]) {
    mkdirSync(path.dirname(filename), { recursive: true });
    writeFileSync(filename, content);
  }
  console.log(`Categorized ${summary.totals.gaps} gaps in ${summary.categories.length} groups; ${summary.totals.versionSkip} version skips kept separate.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
